vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        activitees_images:
            upload_destination: '%kernel.project_dir%/public/images/activitees'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        photos_images:
            upload_destination: '%kernel.project_dir%/public/images/photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
